### ISSUE TITLE
Practice Slot times expressed in UTC are confusing to end users

### ISSUE THREAD

**Issue by djmolny** [International-Aerobatic-Club/website-d7#12]
Although expressing all times in UTC sidesteps all manner of computing problems involving local timezones, it turns out that our testers were all confused by it.

**Comment by djmolny** [comment]
Potential solutions:
- Express times in the contest timezone.
  - But how do we know what timezone the contest is in? Option A: Use the city, state, and country (or perhaps airport lat/long) to infer the timezone. Could be tricky to implement. Option B: Force the contest organizer to explicitly select the timezone. Easier to implement, but could be error-prone.
- Express times in the end user's timezone. Downsides: Potential confusion over home TZ vs contest TZ, and some (how many??) users haven't set their own TZ preference.

**Comment by jtbourke** [comment]
> Potential solutions:
>   * But how do we know what timezone the contest is in? Option A: Use the city, state, and country (or perhaps airport lat/long) to infer the timezone. Could be tricky to implement. Option B: Force the contest organizer to explicitly select the timezone. Easier to implement, but could be error-prone.

B is easier and probably sufficient because the Contest Organizer can make the fix themselves.  It's a reasonable expectation that if they enter the wrong time zone and see a problem that they will remember what they did and fix it. 

> * Express times in the end user's timezone. Downsides: Potential confusion over home TZ vs contest TZ, and some (how many??) users haven't set their own TZ preference.

I think this would not be worthwhile because it seems contrary to my expectations as a user.  If I book a flight to a different time zone I see the arrival time in the time zone of the arrival airport, not my own.  If I book a concert ticket I see the times in local time as well.

**Comment by djmolny** [comment]
Fixed by commit 7521e0daaae20b88d0136bbfc08de4e434862ede
